datasetSetting:
  method: UniversalDatasetMethod
  parameter: 
    name: Flower102
    infoLoaderList:
      - setName: trainset
        name: loadClsTextInfo
        parameter:
          textPath: dataprocess/Flower102/textClean/train
      - setName: validset
        name: loadClsTextInfo
        parameter:
          textPath: dataprocess/Flower102/textClean/val
      - name: loadClsCategoryList
        parameter:
          path: dataprocess/Flower102/textClean/train
      - name: loadTextEncodeDict
        parameter:
          pathList: 
            - dataprocess/Flower102/textClean/train
            - dataprocess/Flower102/textClean/val
    datasetList:
      - setName: trainset
        name: TextDataset
      - setName: trainset
        name: LabelDataset
      - setName: validset
        name: TextDataset
      - setName: validset
        name: LabelDataset

    collateFn:
      - textCollateFn
      - labelCollateFn
modelSetting: 
  name: TextCNN
  parameter: {}
optimizerSetting: 
  # name: SGD
  name: RAdam
  parameter:
    lr: 0.005
    # momentum: 0.9
    weight_decay: 0.00001
lossSetting : 
  method: CrossEntropyLoss
  parameter: {}
trainSetting: 
  method: SupervisedLearning
  metrics: [AccuracyCls]
  metricsParameter: []
  decayMethod:
    name: CosineDecay
  loader: 
    batch_size: 4
    num_workers: 2
    shuffle: true
validSetting : 
  metrics: [AccuracyCls]
  metricsParameter: []
  interval: 5
  loader: 
    batch_size: 8
    num_workers: 2
    shuffle: false
saveMethod:
  setName: valid
  calName: AccuracyCls
  minimize: false
testSetting:
  method: SupervisedTest
  loader: 
    batch_size: 8
    num_workers: 2
    shuffle: false
evaluateSetting:
  method:
  - ClassificationEvaluate
  setName: validset 
epochs: 50